# Generated by Django 3.0.8 on 2020-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201126_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='udata',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udata',
            name='mobile',
            field=models.CharField(default='No mobile provided', max_length=10),
            preserve_default=False,
        ),
    ]
