# Generated by Django 3.0.8 on 2020-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201126_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='udata',
            name='city',
            field=models.CharField(default='City Not Provided', max_length=255),
            preserve_default=False,
        ),
    ]
